Repository SWPC-Team-You-Can-Do-It/ppurisam-Frontend, pull requests merged in 2024-11, with the labels that each got.

#33 feat: 음성 인식 백엔드 연동
  src/components/send/ImageCreate/ImageCreate.jsx
Labels: feature

#37 refactor: 이미지생성 모달창 버튼ui 수정
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
Labels: refactor

#43 refactor:문자 보내기, 주소록 수정
  package-lock.json
  package.json
  src/assets/images/contact/Message.png
  src/components/contact/Contact.css
  src/components/contact/Contact.jsx
  src/components/contact/ContactData.js
  src/components/send/SendPageContact/SendPageContact.css
  src/components/send/SendPageContact/SendPageContact.jsx
Labels: refactor

#47 feat: 사용자 로그인 연동
  src/App.jsx
  src/components/login/AuthContext.jsx
  src/components/login/Login.jsx
  src/components/login/axiosInstance.js
  src/components/login/privateRoute.jsx
  src/components/main/Header/Header.jsx
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/MessageCreate/MessageCreate.jsx
  src/components/send/MessageSend/MessageSend.jsx
  src/components/send/SendPageContact/SendPageContact.css
  src/index.css
  src/index.js
  src/main.jsx
Labels: feature

#49 feat: 메시지 생성 음성녹음기능 추가
  src/components/login/axiosInstance.js
  src/components/send/MessageCreate/MessageCreate.jsx
  src/components/send/MessageSend/MessageSend.jsx
Labels: feature

#51 refactor: axios 인터셉터 수정
  src/components/login/axiosInstance.js
  src/components/main/Header/Header.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/MessageCreate/MessageCreate.jsx
  src/components/send/MessageSend/MessageSend.jsx
Labels: refactor

#53 feat: 주소록 연동 기능 구현
  src/components/contact/Contact.css
  src/components/contact/Contact.jsx
  src/components/contact/ContactData.js
  src/components/contact/Contacts/Contacts.css
  src/components/contact/Contacts/Contacts.jsx
  src/components/contact/EditContactModal/EditContactModal.css
  src/components/contact/EditContactModal/EditContactModal.jsx
  src/components/contact/InputContacts/InputContacts.css
  src/components/contact/InputContacts/InputContacts.jsx
  src/components/contact/ManageContacts/ManageContacts.css
  src/components/contact/ManageContacts/ManageContacts.jsx
  src/pages/ContactPage/ContactPage.css
  src/pages/ContactPage/ContactPage.jsx
Labels: feature, refactor

#59 feat: 마이페이지 연동
  src/components/my/My.jsx
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/MessageCreate/MessageCreate.jsx
Labels: feature

#61 feat: 텍스트 생성후 결과값 이미지에 넘겨주기
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/MessageSend/MessageSend.jsx
  src/pages/SendPage/SendPage.jsx
Labels: feature

#63 feat:문자보내기 주소록 연동구현
  src/components/send/SendPageContact/AddressBookModal.css
  src/components/send/SendPageContact/AddressBookModal.jsx
  src/components/send/SendPageContact/SendPageContact.jsx
Labels: feature

#65 feat: 챗봇 ui 구현
  package-lock.json
  package.json
  src/App.jsx
  src/components/chatbot/Chatbot.css
  src/components/chatbot/Chatbot.jsx
  src/components/chatbot/Robot.css
  src/components/chatbot/Robot.jsx
Labels: feature

#71 refactor: 수정하기 삭제
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/MessageCreate/MessageCreate.jsx
Labels: refactor

#83 feat: 이미지 테마 선택
  src/components/login/axiosInstance.js
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ThemeSelection/ThemeSelectionModal.css
  src/components/send/ThemeSelection/ThemeSelectionModal.jsx
Labels: feature

#89 feat:챗봇 음성인식 기능 추가, ai텍스트 생성 연동 기능 구현
  docker-compose.yml
  src/components/chatbot/Chatbot/Chatbot.css
  src/components/chatbot/Chatbot/Chatbot.jsx
  src/components/chatbot/Chatbot/ChatbotMessage.css
  src/components/chatbot/Chatbot/ChatbotMessage.jsx
  src/components/chatbot/EasySmsButton/EasySmsButton.css
  src/components/chatbot/EasySmsButton/EasySmsButton.jsx
Labels: feature

#93 feat: 이미지 텍스트추가
  package-lock.json
  package.json
  src/components/main/Slider/Slider.jsx
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.css
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/TextImage/TextOptions.css
  src/components/send/TextImage/TextOptions.jsx
  src/components/send/TextImage/TextOverlay.css
  src/components/send/TextImage/TextOverlay.jsx
  vite.config.js
Labels: feature

#95 bug: vite 설정 수정
  vite.config.js
Labels: bug

#97 bug: vite 설정파일 수정
  vite.config.js
Labels: bug, refactor

#101 feat: 메시지 테마 선택기능
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/MessageCreate/MessageCreate.css
  src/components/send/MessageCreate/MessageCreate.jsx
  src/components/send/ThemeSelection/ImageThemeSelectionModal.css
  src/components/send/ThemeSelection/ImageThemeSelectionModal.jsx
  src/components/send/ThemeSelection/TextThemeSelectionModal.css
  src/components/send/ThemeSelection/TextThemeSelectionModal.jsx
Labels: feature

#105 refactor: 메시지 테마 선택 코드 수정
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.css
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/MessageSend/MessageSend.css
  src/components/send/MessageSend/MessageSend.jsx
  src/components/send/SendPageContact/AddressBookModal.css
  src/components/send/SendPageContact/SendPageContact.jsx
  src/components/send/TextImage/TextOptions.css
  src/components/send/TextImage/TextOverlay.css
  src/components/send/TextImage/TextOverlay.jsx
  src/components/send/ThemeSelection/ImageThemeSelectionModal.jsx
  src/components/send/ThemeSelection/TextThemeSelectionModal.jsx
  src/pages/SendPage/SendPage.css
  src/pages/SendPage/SendPage.jsx
  vite.config.js
Labels: bug, feature, refactor

#109 refactor: 텍스트, 이미지 생성 모달창 수정
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/MessageCreate/MessageCreate.css
Labels: refactor

#115 refactor: 문자 보내기 필요없는 부분 제거
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/MessageSend/MessageSend.jsx
  src/pages/SendPage/SendPage.jsx
Labels: refactor

#117 refactor: UI수정
  src/components/chatbot/AddContactButton/AddContactButton.css
  src/components/chatbot/AddContactButton/AddContactButton.jsx
  src/components/chatbot/Chatbot/Chatbot.css
  src/components/chatbot/EasySmsButton/EasySmsButton.css
  src/components/chatbot/EasySmsButton/EasySmsButton.jsx
  src/components/chatbot/ServiceDescriptionButton/ServiceDescriptionButton.css
  src/components/chatbot/ServiceDescriptionButton/ServiceDescriptionButton.jsx
  src/components/contact/Contacts/Contacts.css
  src/components/contact/ManageContacts/ManageContacts.css
  src/components/send/SendPageContact/AddressBookModal.css
  src/components/send/SendPageContact/SendPageContact.css
Labels: refactor

#119 bug: 이미지 사용하기 오류 수정
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/TextImage/TextOptions.jsx
  src/components/send/TextImage/TextOverlay.css
  src/components/send/TextImage/TextOverlay.jsx
Labels: bug

#121 feat: 업로드 이미지 형식 변환
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/SendPageContact/SendPageContact.jsx
Labels: feature

#123 refactor: 메시지 생성 모달 ui 수정
  src/components/send/MessageCreate/MessageCreate.css
Labels: refactor

#125 bug: 텍스트 위치조정오류 수정
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/TextImage/TextOverlay.css
  src/components/send/TextImage/TextOverlay.jsx
Labels: bug, refactor

#129 feat: 이미지 위에 텍스트 올리기
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.jsx
Labels: feature

#131 feat: 폰트 추가
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/TextImage/TextOptions.css
  src/components/send/TextImage/TextOptions.jsx
  src/fonts/GmarketSansLight.otf
  src/fonts/LINESeedKR-Rg.otf
  src/fonts/Pretendard-Regular.otf
  src/fonts/Pretendard-Regular.woff2
  src/index.css
  src/main.jsx
Labels: feature
