Repository SWPC-Team-You-Can-Do-It/ppurisam-Frontend, pull requests merged in 2024-10, with the labels that each got.

#2 setting: Dockerfile 추가
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: setting

#4 setting: vite 설정
  Dockerfile
  docker-compose.yml
  index.html
  package-lock.json
  package.json
  public/index.html
  src/App.jsx
  src/main.jsx
  vite.config.js
Labels: setting

#13 feat: 발송조회 페이지 구현
  src/App.jsx
  src/assets/images/tracking/Polygon.png
  src/components/main/Header/Header.css
  src/components/main/Header/Header.jsx
  src/components/main/Send/ImageSend/ImageSend.css
  src/components/send/ImageSend/ImageSend.css
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/MessageSend/MessageSend.css
  src/components/send/MessageSend/MessageSend.jsx
  src/components/tracking/TrackData.js
  src/components/tracking/Tracking.css
  src/components/tracking/Tracking.jsx
  src/pages/SendPage/SendPage.css
  src/pages/SendPage/SendPage.jsx
  src/pages/TrackingPage/TrackingPage.css
  src/pages/TrackingPage/TrackingPage.jsx
  vite.config.js
Labels: feature

#17 feat: 텍스트, 이미지 프롬프트 (생성, 수정) 모달창 추가 + 사진 업로드 기능 추가
  index.html
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/components/send/ImageSend/ImageSend.css
  src/components/send/ImageSend/ImageSend.jsx
  src/components/send/MessageCreate/MessageCreate.css
  src/components/send/MessageCreate/MessageCreate.jsx
  src/components/send/MessageSend/MessageSend.css
  src/components/send/MessageSend/MessageSend.jsx
Labels: feature

#19 refactor:주소록 구조 수정
  src/App.jsx
  src/assets/images/contact/Pen.png
  src/assets/images/contact/Upload.png
  src/assets/images/contact/folder.png
  src/assets/images/contact/icon_arrow.png
  src/assets/images/contact/mail.png
  src/assets/images/contact/phone.png
  src/assets/images/contact/search.png
  src/assets/images/contact/trash.png
  src/assets/images/contact/user.png
  src/components/contact/Contact.css
  src/components/contact/Contact.jsx
  src/pages/ContactPage/ContactPage.css
  src/pages/ContactPage/ContactPage.jsx
Labels: refactor

#28 feat:문자 보내기 하단부분 및 주소록 모달창 구현 + 기존 코드 수정
  src/components/contact/Contact.css
  src/components/main/Header/Header.jsx
  src/components/send/MessageSend/MessageSend.css
  src/components/send/MessageSend/MessageSend.jsx
  src/components/send/SendPageContact/AddressBookModal.css
  src/components/send/SendPageContact/AddressBookModal.jsx
  src/components/send/SendPageContact/SendPageContact.css
  src/components/send/SendPageContact/SendPageContact.jsx
  src/pages/SendPage/SendPage.css
  src/pages/SendPage/SendPage.jsx
Labels: feature, refactor

#29 feat: 웹에서 음성 녹음파일 생성
  package-lock.json
  package.json
  src/components/send/ImageCreate/ImageCreate.css
  src/components/send/ImageCreate/ImageCreate.jsx
  src/utils/useAudioRecorder.js
Labels: feature

#31 feat: 마이페이지 화면 구현
  src/App.jsx
  src/assets/images/My/Trash.png
  src/components/my/My.css
  src/components/my/My.jsx
  src/pages/MyPage/MyPage.css
  src/pages/MyPage/MyPage.jsx
Labels: feature
